config/routes.rb
Rails.application.routes.draw do
  get 'cases/new'

  get 'cases/show'

  get 'cases/edit'

  get 'cases/update'

  get 'cases/destroy'

 root 'mainpage#index'

 get '/tutors', to: 'tutors#new'
 get '/students', to: 'students#new'

 
 resources :tutors 
 get '/tutor_login', to: 'tutor_sessions#new'
 post '/tutor_login', to: 'tutor_sessions#create'
 delete '/tutor_logout', to: 'tutor_sessions#destroy'

 resources :students do 
 	resources :cases
 end 
 
 get '/student_login', to: 'student_sessions#new'
 post '/student_login', to: 'student_sessions#create'
 delete '/student_logout', to: 'student_sessions#destroy'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password
  has_many :cases 

  validates :name, :email, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false },
  					format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  VALID_MOBILE_REGEX = /\A^[569][0-9]{7}$\z/i
  validates :mobile_no, length: { minimum: 8 }, format: { with: VALID_MOBILE_REGEX }	
  validates :address, length: { maximum: 255, minimum: 5 }
  validates :contact_name, length: { minimum: 3 }

  enum relation: {
		"Self"      => 0,
		"Parent"    => 1,
		"Sibling"   => 2,
		"Family"	=> 3,
		"Friend"	=> 4,
		"Others"	=> 5
	}

	enum district: {
		"Central" 		=> 0,
		"Eastern" 		=> 1,
		"Southern" 		=> 2,
		"Wan Chai" 		=> 3,
		"Sham Shui Po"	=> 4,
		"Kowloon City" 	=> 5,
		"Kwun Tong"		=> 6,
		"Wong Tai Sin" 	=> 7,
		"Yau Tsim Mong" => 8,
		"Islands" 		=> 9,
		"Kwai Tsing"	=> 10,
		"North"			=> 11,
		"Sha Tin"		=> 12,
		"Tai Po"		=> 13,
		"Tsuen Wan" 	=> 14,
		"Tuen Mun" 		=> 15,
		"Yuen Long" 	=> 16
	}
end

app/models/tutor.rb
class Tutor < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
  					format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper
  include StudentsHelper
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_student

  def new
    @case = @student.cases.build
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def set_student
      @student = Student.find(params[:student_id])
    end

    def case_params
      params.require(:case).permit(:categories, :Level_genearl, :level_oral, :level_music,
                                  :level_other, :subject_general, :subject_oral, :subject_music,
                                  :subject_other, :no_of_student, :freq_of_lesson, :lesson_time,
                                  :tuition_fee, :tuition_per, :min_edu_level, :tutor_gender, 
                                  :other_info)
    end
end

app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
	def index
	end
end

app/controllers/student_sessions_controller.rb
class StudentSessionsController < ApplicationController

	def new
	end

	def create
		student = Student.find_by(name: params[:session][:name])
		if student && student.authenticate(params[:session][:password])
			log_in student
			redirect_to student_path(student)
		else
			flash[:danger] = "Invalid email/password combination"
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def destroy
		log_out
		redirect_to root_url
	end

	private

		def set_param
			params.require(:session).permit(:name, :password)
		end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	before_action :set_student, except: [:new, :create]

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)

		if @student.save
			flash[:notice] = "成功註冊"
			redirect_to student_path(@student)
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @student.update_attributes(student_params)
			flash[:success] = "Profile updated"
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
	end

	private

		def student_params
			params.require(:student).permit(:name, :email, :password, :password_confirmation, :contact_name, :mobile_no, :relation, :district, :address)
		end

		def set_student
			@student = Student.find(params[:id])
		end
end

app/controllers/tutor_sessions_controller.rb
class TutorSessionsController < ApplicationController
	def new
	end

	def create
		tutor = Tutor.find_by(name: params[:session][:name])
		if tutor && tutor.authenticate(params[:session][:password])
			log_in(tutor)
			redirect_to tutor_path(tutor)
		else
			flash[:danger] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end

	private

		def set_param
			paras.require(:session).permit(:name, :password)
		end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
	before_action :set_tutor, only: [:show, :edit, :destroy]

	def new
		@tutor = Tutor.new
	end

	def create
		@tutor = Tutor.new(tutor_params)

		if @tutor.save
			flash[:notice] = "You have successfully signed up as a Smart Tutor!"
			log_in @tutor
			redirect_to tutor_path(@tutor)
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def destroy
	end

	private

		def tutor_params
			params.require(:tutor).permit(:name, :email, :password, :password_confirmation)
		end

		def set_tutor
			@tutor = Tutor.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= (Tutor.find_by(id: session[:user_id]) || Student.find_by(id: session[:user_id]))
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def tutor?
		if @current_user.class == :tutor
			true
		else
			false
		end
	end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/helpers/student_sessions_helper.rb
module StudentSessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper


end

app/helpers/tutor_sessions_helper.rb
module TutorSessionsHelper
	
end

app/helpers/tutors_helper.rb
module TutorsHelper

end

app/views/cases/destroy.html.erb
<h1>Cases#destroy</h1>
<p>Find me in app/views/cases/destroy.html.erb</p>

app/views/cases/edit.html.erb
<h1>Cases#edit</h1>
<p>Find me in app/views/cases/edit.html.erb</p>

app/views/cases/new.html.erb
<h1>Cases#new</h1>
<p>Find me in app/views/cases/new.html.erb</p>

app/views/cases/show.html.erb
<h1>Cases#show</h1>
<p>Find me in app/views/cases/show.html.erb</p>

app/views/cases/update.html.erb
<h1>Cases#update</h1>
<p>Find me in app/views/cases/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">
      <h1>Smart Tutor</h1>
    </div>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
        <% if logged_in? %>
          <%= render "students/nav" %>
        <% else %>
          <li class="active"><a href="#">Home</a></li>
          <li><% link_to "Find Tutor", "#" %></li>
          <li><a href="#">Link</a></li>
        <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <% if tutor? %>
              <li><%= link_to "Logout", tutor_logout_path, method: :delete %></li>
              <li><%= link_to "Edit Profile", "#" %></li>
            <% else %>
              <li><%= link_to "Logout", student_logout_path, method: :delete %></li>
              <li><%= link_to "Edit Profile", edit_student_path(@current_user) %></li>
            <% end %>
          <% else %>

            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> Sign up <span class="caret"></span></a>

              <ul class="dropdown-menu">
                <li><%= link_to "Sign up as Student/Parent", new_student_path, class: "label-warning" %></li>
                <li><%= link_to "Sign up as Tutor", new_tutor_path, class: "label-warning" %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-log-in"></span> Login <span class="caret"></span></a>

              <ul class="dropdown-menu">
                <li><%= link_to "Login as Student/Parent", student_login_path %></li>
                <li><%= link_to "Login as Tutor", tutor_login_path %></li>
              </ul>
            </li>

          <% end %>
        </ul>
      </div>
    </nav>


    <div class="alert">
    	<% flash.each do |message_type, message| %>
    		<%= content_tag(:div, message, class: "alert alert-success") %>
    	<% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mainpage/index.html.erb
<div class="container">
	
</div>

app/views/student_sessions/_form.html.erb
<h1>Log in</h1>

	<%= form_for(:session, url: student_login_path) do |form| %>

		<div class="form-group">
			<div class="input-group name">
		    	<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		    	<%= form.text_field :name, class: "form-control", :placeholder => "Name"%>
			</div><br/>

			<div class="input-group password">
				<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
				<%= form.password_field :password, class: "form-control", placeholder: "Password" %>
			</div><br/>

			<p class="submit">
				<%= form.submit "Login", class: "btn btn-warning" %>
			</p>

		</div>
	<% end %>

		<p>New user? <%= link_to "Sign up now!", new_student_path %></p>
	</div>
</div>

app/views/student_sessions/new.html.erb
<div>
	<%= render "form" %>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |form| %>
	<% if @student.errors.any? %>
		<div class="error_explanation alert alert-danger">
			<h2><%= pluralize(@student.errors.count, "error") %> occurred:</h2>

			<ul>
				<% @student.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
			<div class="input-group name">
		    	<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		    	<%= form.text_field :name, class: "form-control", :placeholder => "Name"%>
			</div><br/>

			<div class="email input-group">
				<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
				<%= form.email_field :email, class: "form-control", placeholder: "Email" %>
			</div><br/>

			<div class="input-group password">
				<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
				<%= form.password_field :password, class: "form-control", placeholder: "Password" %>
			</div><br/>

			<div class="input-group password">
				<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
				<%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
			</div><br/>

			<p class="submit">
				<%= form.submit "Register", class: "btn btn-warning" %>
			</p>
	</div>
<% end %>

app/views/students/_nav.html.erb
<li class="active"><a href="#">Home</a></li>
<li><%= link_to "Find Tutor",  new_student_case_path(@current_user) %>
<li><a href="#">Link</a></li>

app/views/students/_profile_form.html.erb
<%= form_for(@student) do |form| %>
	<% if @student.errors.any? %>
		<div class="error_explanation alert alert-danger">
			<h2><%= pluralize(@student.errors.count, "error") %> occurred:</h2>

			<ul>
				<% @student.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
			<div class="input-group name">
		    	<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		    	<%= form.text_field :name, class: "form-control", :placeholder => "User name"%>
			</div><br/>

			<div class="email input-group">
				<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
				<%= form.email_field :email, class: "form-control", placeholder: "Email" %>
			</div><br/>

			<div class="input-group password">
				<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
				<%= form.password_field :password, class: "form-control", placeholder: "Password" %>
			</div><br/>

			<div class="input-group password">
				<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
				<%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
			</div><br/>

			<div class="input-group contact_name">
		    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		    <%= form.text_field :contact_name, class: "form-control", :placeholder => "Contact Person"%>
			</div><br/>

			<div class="input-group mobile_no">
				<span class="input-group-addon"><i class="glyphicon glyphicon-phone"></i></span>
				<%= form.telephone_field :mobile_no, class: "form-control", :placeholder => "Contact Person Tel No"%>
			</div><br/>

			<div class="input-group relation">
		    <span class="input-group-addon glyphicon-rel"><i class="glyphicon glyphicon-user"></i></span>
		    <%= form.select :relation, Student.relations.keys, class: "form-control select", prompt: "Relationship with student"%>
			</div><br/>

			<div class="input-group district">
				<span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
				<%= form.select :district, Student.districts.keys, class: "form-control",
					prompt: "Residence District" %>
			</div><br/>

			<div class="input-group address">
				<span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
				<%= form.text_field :address, class: "form-control", :placeholder => "Residence Address" %>
			</div><br/>


			<p class="submit">
				<%= form.submit "Update", class: "btn btn-warning" %>
			</p>
	</div>
<% end %>

app/views/students/edit.html.erb
<h1>Profile Edit</h1>

<div>
 <%= render "profile_form" %>
</div>

app/views/students/new.html.erb
<h1>Sign up as Student/Parent</h1>

<ul class="pager">
  <li class="previous">
   	<%= link_to "Previous", :back %>
  </li>
</ul>

<div>
	<%= render "form" %>
</div>

app/views/students/show.html.erb
<h1>Welcome <%= "#{@student.name}" %></h1>

<h3>Profile</h3>
<table class="table table-striped">

<div class="container">
<tbody>
	<tr>
		<td>User name: </td>
		<td><%= @student.name %></td>
	</tr>
	<tr>
		<td>Email: </td>
		<td><%= @student.email %></td>
	</tr>
	<tr>
		<td>Contact Person : </td>
		<td><%= @student.contact_name %></td>
	</tr>
	<tr>
		<td>Contact Person Tel No : </td>
		<td><%= @student.mobile_no %></td>
	</tr>
	<tr>
		<td>Relationship with student : </td>
		<td><%= @student.relation %></td>
	</tr>
	<tr>
		<td>Residence District : </td>
		<td><%= @student.district %></td>
	</tr>
	<tr>
		<td>Residence Address : </td>
		<td><%= @student.address %></td>
	</tr>
</tbody>
</table>
</div>

app/views/tutor_sessions/_form.html.erb
<h1>Log in</h1>

	<%= form_for(:session, url: tutor_login_path) do |form| %>

		<div class="form-group">
			<div class="input-group name">
		    	<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
		    	<%= form.text_field :name, class: "form-control", :placeholder => "Name"%>
			</div><br/>

			<div class="input-group password">
				<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
				<%= form.password_field :password, class: "form-control", placeholder: "Password" %>
			</div><br/>

			<p class="submit">
				<%= form.submit "Login", class: "btn btn-warning" %>
			</p>

		</div>
	<% end %>

		<p>New user? <%= link_to "Sign up now!", new_tutor_path %></p>
	</div>
</div>

app/views/tutor_sessions/new.html.erb
<div>
	<%= render "form" %>
</div>

app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |form| %>
	<% if @tutor.errors.any? %>
		<div class="error_explanation alert alert-danger">
			<h2><%= pluralize(@tutor.errors.count, "error") %> occurred:</h2>

			<ul>
				<% @tutor.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<div class="input-group name">
	    	<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
	    	<%= form.text_field :name, class: "form-control", :placeholder => "Name"%>
		</div><br/>

		<div class="email input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
			<%= form.email_field :email, class: "form-control", placeholder: "Email" %>
		</div><br/>

		<div class="input-group password">
			<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
			<%= form.password_field :password, class: "form-control", placeholder: "Password" %>
		</div><br/>

		<div class="input-group password">
			<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
			<%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
		</div><br/>

		<p class="submit">
			<%= form.submit "Register", class: "btn btn-warning" %>
		</p>
	</div>
<% end %>

app/views/tutors/new.html.erb
<h1>Sign Up as a Smart Tutor today!</h1>

<ul class="pager">
  <li class="previous">
   	<%= link_to "Previous", :back %>
  </li>
</ul>

<div>
	<%= render "form" %>
</div>

app/views/tutors/show.html.erb
<h1>Welcome <%= "#{@tutor.name}" %></h1>